import type { Ingredient, Recipe } from "@/lib/types";

function ingredient(amount: string, item: string, aisle: Ingredient["aisle"]): Ingredient {
  return { amount, item, aisle };
}

export const RECIPES: Recipe[] = [
  {
    id: "lemon-chickpea-skillet",
    title: "Lemon chickpea skillet",
    blurb: "A bright one-pan dinner that lands on the table while the rice is still steaming.",
    slot: "dinner",
    minutes: 20,
    cuisine: "Mediterranean",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "weeknight"],
    ingredients: [
      ingredient("1 cup", "rice", "pantry"),
      ingredient("1 can", "chickpeas", "protein"),
      ingredient("3 cups", "spinach", "produce"),
      ingredient("1", "lemon", "produce"),
      ingredient("3 cloves", "garlic", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
      ingredient("1 tsp", "cumin", "pantry"),
    ],
    steps: [
      "Rinse the rice and start it simmering in lightly salted water.",
      "Warm olive oil in a skillet and soften the garlic for about a minute.",
      "Add drained chickpeas, cumin, and a pinch of salt. Stir until they smell toasty.",
      "Fold in spinach and the juice of the lemon. Serve over rice with the remaining lemon.",
    ],
  },
  {
    id: "coconut-red-lentil-dal",
    title: "Coconut red lentil dal",
    blurb: "A 30-minute dal finished with coconut milk, ginger, and cilantro.",
    slot: "dinner",
    minutes: 30,
    cuisine: "Indian",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "weeknight"],
    ingredients: [
      ingredient("1 cup", "red lentils", "protein"),
      ingredient("1 can", "coconut milk", "pantry"),
      ingredient("1 cup", "rice", "pantry"),
      ingredient("1", "tomato", "produce"),
      ingredient("1 tbsp", "ginger", "produce"),
      ingredient("2 cloves", "garlic", "produce"),
      ingredient("1 tsp", "turmeric", "pantry"),
      ingredient("1 tsp", "cumin", "pantry"),
      ingredient("1 handful", "cilantro", "produce"),
    ],
    steps: [
      "Rinse the lentils, then simmer them with turmeric and enough water to cover by an inch.",
      "Start the rice in a separate pot.",
      "Stir in chopped tomato, ginger, garlic, cumin, and coconut milk. Simmer until creamy.",
      "Salt to taste and finish with cilantro.",
    ],
  },
  {
    id: "sweet-potato-black-bean-tacos",
    title: "Sweet potato black bean tacos",
    blurb: "Weeknight tacos on corn tortillas, with cabbage instead of a creamy sauce.",
    slot: "dinner",
    minutes: 25,
    cuisine: "Mexican",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "weeknight"],
    ingredients: [
      ingredient("1", "sweet potato", "produce"),
      ingredient("1 can", "black beans", "protein"),
      ingredient("8", "corn tortillas", "pantry"),
      ingredient("2 cups", "cabbage", "produce"),
      ingredient("1", "lime", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
      ingredient("1 tsp", "cumin", "pantry"),
      ingredient("1 tsp", "chili powder", "pantry"),
    ],
    steps: [
      "Dice the sweet potato and roast or skillet-cook it in olive oil with cumin and chili powder.",
      "Warm the black beans with a splash of water and a squeeze of lime.",
      "Heat the corn tortillas in a dry pan.",
      "Fill tortillas with sweet potato, beans, and cabbage. Finish with more lime.",
    ],
  },
  {
    id: "miso-ginger-tofu-bowls",
    title: "Miso ginger tofu bowls",
    blurb: "A Japanese-leaning bowl with tamari, miso, and ginger over rice.",
    slot: "dinner",
    minutes: 25,
    cuisine: "Japanese",
    vegetarian: true,
    contains: ["soy"],
    tags: ["vegetarian", "weeknight"],
    ingredients: [
      ingredient("14 oz", "tofu", "protein"),
      ingredient("1 tbsp", "miso paste", "pantry"),
      ingredient("1 tbsp", "tamari", "pantry"),
      ingredient("1 cup", "rice", "pantry"),
      ingredient("2 cups", "broccoli", "produce"),
      ingredient("1 tbsp", "ginger", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Cube the tofu and pat it dry. Start the rice.",
      "Sear the tofu in olive oil until the edges are golden.",
      "Stir miso, tamari, and grated ginger with a spoon of warm water. Toss it with the tofu.",
      "Steam or skillet the broccoli and serve everything over rice.",
    ],
  },
  {
    id: "tomato-white-bean-pasta",
    title: "Tomato white bean pasta",
    blurb: "Pantry pasta with white beans, tomato, and basil.",
    slot: "dinner",
    minutes: 20,
    cuisine: "Italian",
    vegetarian: true,
    contains: ["gluten"],
    tags: ["vegetarian", "weeknight"],
    ingredients: [
      ingredient("8 oz", "pasta", "pantry"),
      ingredient("1 can", "cannellini beans", "protein"),
      ingredient("2", "tomato", "produce"),
      ingredient("2 cloves", "garlic", "produce"),
      ingredient("1 handful", "basil", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Boil the pasta in salted water.",
      "Soften garlic in olive oil, then add chopped tomato and a pinch of salt.",
      "Stir in drained cannellini beans and a splash of pasta water.",
      "Toss with the pasta and basil. Taste before you add anything from a shared condiment shelf.",
    ],
  },
  {
    id: "sheet-pan-fajita-vegetables",
    title: "Sheet-pan fajita vegetables",
    blurb: "Eggplant, peppers, and cauliflower roasted hot, then piled on corn tortillas.",
    slot: "dinner",
    minutes: 25,
    cuisine: "Mexican",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "weeknight"],
    ingredients: [
      ingredient("1", "eggplant", "produce"),
      ingredient("2", "bell pepper", "produce"),
      ingredient("1", "red onion", "produce"),
      ingredient("2 cups", "cauliflower", "produce"),
      ingredient("6", "corn tortillas", "pantry"),
      ingredient("1 tbsp", "olive oil", "pantry"),
      ingredient("1 tsp", "cumin", "pantry"),
      ingredient("1", "lime", "produce"),
    ],
    steps: [
      "Heat the oven to 425°F. Chop the vegetables into bite-size pieces.",
      "Toss with olive oil, cumin, and salt. Roast until the edges brown, about 18 minutes.",
      "Warm the corn tortillas.",
      "Squeeze lime over the tray and eat it straight from the pan or in tortillas.",
    ],
  },
  {
    id: "quinoa-kale-harvest-bowl",
    title: "Quinoa kale harvest bowl",
    blurb: "A sturdy bowl with apple, kale, and pumpkin seeds when you want dinner without a sauce.",
    slot: "dinner",
    minutes: 25,
    cuisine: "American",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "weeknight"],
    ingredients: [
      ingredient("1 cup", "quinoa", "pantry"),
      ingredient("3 cups", "kale", "produce"),
      ingredient("1", "apple", "produce"),
      ingredient("2 tbsp", "pumpkin seeds", "pantry"),
      ingredient("1 tbsp", "olive oil", "pantry"),
      ingredient("1", "lemon", "produce"),
    ],
    steps: [
      "Simmer quinoa in water until the tails unfurl, then drain any extra liquid.",
      "Massage chopped kale with olive oil, lemon juice, and a pinch of salt.",
      "Dice the apple.",
      "Pile kale and apple over the quinoa and scatter pumpkin seeds on top.",
    ],
  },
  {
    id: "thai-coconut-lime-vegetables",
    title: "Coconut lime vegetable skillet",
    blurb: "Thai-leaning vegetables in coconut milk, lime, and ginger.",
    slot: "dinner",
    minutes: 25,
    cuisine: "Thai",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "weeknight"],
    ingredients: [
      ingredient("1 can", "coconut milk", "pantry"),
      ingredient("2 cups", "snap peas", "produce"),
      ingredient("1", "bell pepper", "produce"),
      ingredient("1 cup", "rice", "pantry"),
      ingredient("1", "lime", "produce"),
      ingredient("1 tbsp", "ginger", "produce"),
      ingredient("1 handful", "basil", "produce"),
      ingredient("1 tsp", "chili flakes", "pantry"),
    ],
    steps: [
      "Start the rice.",
      "Simmer coconut milk with ginger, chili flakes, and a pinch of salt.",
      "Add sliced pepper and snap peas and cook until just tender.",
      "Finish with lime juice and basil.",
    ],
  },
  {
    id: "garlic-herb-chicken",
    title: "Garlic herb chicken with green beans",
    blurb: "A straightforward skillet for nights when Alex is fine with chicken.",
    slot: "dinner",
    minutes: 30,
    cuisine: "American",
    vegetarian: false,
    contains: [],
    tags: ["chicken", "weeknight"],
    ingredients: [
      ingredient("1 lb", "chicken thighs", "protein"),
      ingredient("3 cloves", "garlic", "produce"),
      ingredient("1", "lemon", "produce"),
      ingredient("3 cups", "green beans", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
      ingredient("1 tsp", "paprika", "pantry"),
    ],
    steps: [
      "Season the chicken with salt, paprika, and a little lemon zest.",
      "Sear it in olive oil until cooked through, then rest it on a plate.",
      "In the same pan, cook garlic and green beans until the beans blister.",
      "Squeeze lemon over both and serve together.",
    ],
  },
  {
    id: "turkey-taco-skillet",
    title: "Turkey taco skillet",
    blurb: "Ground turkey, beans, corn, and salsa over rice.",
    slot: "dinner",
    minutes: 25,
    cuisine: "Mexican",
    vegetarian: false,
    contains: [],
    tags: ["turkey", "weeknight"],
    ingredients: [
      ingredient("1 lb", "ground turkey", "protein"),
      ingredient("1 can", "black beans", "protein"),
      ingredient("1 cup", "corn", "produce"),
      ingredient("1 cup", "rice", "pantry"),
      ingredient("1 tsp", "cumin", "pantry"),
      ingredient("1/2 cup", "salsa", "pantry"),
    ],
    steps: [
      "Start the rice.",
      "Brown the turkey with cumin and salt, breaking it into small pieces.",
      "Stir in black beans, corn, and salsa. Simmer for a few minutes.",
      "Serve over rice. Check the salsa label for surprise allergens.",
    ],
  },
  {
    id: "lemon-herb-cod",
    title: "Lemon herb cod with potatoes",
    blurb: "A fast fish dinner. Skip it entirely if fish is on the allergy list.",
    slot: "dinner",
    minutes: 25,
    cuisine: "Mediterranean",
    vegetarian: false,
    contains: ["fish"],
    tags: ["fish", "weeknight"],
    ingredients: [
      ingredient("1 lb", "cod", "protein"),
      ingredient("2", "potato", "produce"),
      ingredient("1", "lemon", "produce"),
      ingredient("1 handful", "parsley", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
      ingredient("2 cloves", "garlic", "produce"),
    ],
    steps: [
      "Dice the potatoes and boil them until tender.",
      "Season the cod with salt, garlic, and lemon.",
      "Pan-cook the cod in olive oil until it flakes.",
      "Toss potatoes with parsley and olive oil and serve with the cod.",
    ],
  },
  {
    id: "slow-mushroom-ragu",
    title: "Slow mushroom ragù",
    blurb: "A long Sunday sauce. It is here so short weeknights can leave it off the plan.",
    slot: "dinner",
    minutes: 75,
    cuisine: "Italian",
    vegetarian: true,
    contains: ["gluten"],
    tags: ["vegetarian", "weekend"],
    ingredients: [
      ingredient("8 oz", "pasta", "pantry"),
      ingredient("1 lb", "mushrooms", "produce"),
      ingredient("2", "tomato", "produce"),
      ingredient("3 cloves", "garlic", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
      ingredient("1 tsp", "thyme", "pantry"),
    ],
    steps: [
      "Brown sliced mushrooms in olive oil until they give up their liquid.",
      "Add garlic, thyme, and chopped tomato. Simmer until thick, about an hour.",
      "Boil the pasta near the end.",
      "Toss the pasta with the ragù and a splash of pasta water.",
    ],
  },
  {
    id: "peanut-satay-noodles",
    title: "Peanut satay noodles",
    blurb: "A deliberately unsafe fixture used only to prove the peanut filter rejects it.",
    slot: "dinner",
    minutes: 20,
    cuisine: "Thai",
    vegetarian: true,
    contains: ["peanut", "soy", "gluten"],
    tags: ["unsafe-fixture"],
    ingredients: [
      ingredient("8 oz", "wheat noodles", "pantry"),
      ingredient("1/4 cup", "peanut butter", "protein"),
      ingredient("1 tbsp", "soy sauce", "pantry"),
      ingredient("2 cups", "cabbage", "produce"),
      ingredient("1", "lime", "produce"),
    ],
    steps: [
      "Boil the noodles.",
      "Stir peanut butter with soy sauce, lime, and warm water.",
      "Toss the noodles and cabbage in the satay sauce.",
      "This dish must never be served to someone with a peanut allergy.",
    ],
  },
  {
    id: "garlic-shrimp-skillet",
    title: "Garlic shrimp skillet",
    blurb: "A deliberately unsafe fixture used only to prove the shellfish filter rejects it.",
    slot: "dinner",
    minutes: 20,
    cuisine: "Italian",
    vegetarian: false,
    contains: ["shellfish", "gluten"],
    tags: ["unsafe-fixture"],
    ingredients: [
      ingredient("1 lb", "shrimp", "protein"),
      ingredient("8 oz", "pasta", "pantry"),
      ingredient("3 cloves", "garlic", "produce"),
      ingredient("1", "lemon", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Boil the pasta.",
      "Cook shrimp in olive oil with garlic until pink.",
      "Toss with pasta and lemon.",
      "This dish must never be served to someone with a shellfish allergy.",
    ],
  },
  {
    id: "kiwi-lime-chicken",
    title: "Kiwi lime chicken",
    blurb: "Chicken with fresh kiwi. Useful when a custom allergy needs a hard stop.",
    slot: "dinner",
    minutes: 25,
    cuisine: "American",
    vegetarian: false,
    contains: [],
    tags: ["chicken"],
    ingredients: [
      ingredient("1 lb", "chicken thighs", "protein"),
      ingredient("2", "kiwi", "produce"),
      ingredient("1", "lime", "produce"),
      ingredient("1 cup", "rice", "pantry"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Start the rice.",
      "Sear the chicken in olive oil until cooked through.",
      "Dice the kiwi and toss it with lime juice.",
      "Spoon the kiwi over the chicken and serve with rice.",
    ],
  },
  {
    id: "berry-oat-bowl",
    title: "Berry oat bowl",
    blurb: "A five-ingredient breakfast. Oats can pick up gluten in processing, so this stays off gluten-free plans.",
    slot: "breakfast",
    minutes: 10,
    cuisine: "American",
    vegetarian: true,
    contains: ["gluten"],
    tags: ["vegetarian", "breakfast"],
    ingredients: [
      ingredient("1 cup", "rolled oats", "pantry"),
      ingredient("1 cup", "berries", "produce"),
      ingredient("1 tbsp", "maple syrup", "pantry"),
    ],
    steps: [
      "Simmer the oats in water until they are soft.",
      "Stir until thick.",
      "Top with berries and maple syrup.",
      "Read the oat label if gluten is a problem in the house.",
    ],
  },
  {
    id: "cinnamon-rice-porridge",
    title: "Cinnamon rice porridge",
    blurb: "Leftover-rice energy: warm, cinnamon-scented, and free of the big nine.",
    slot: "breakfast",
    minutes: 15,
    cuisine: "American",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "breakfast"],
    ingredients: [
      ingredient("1 cup", "rice", "pantry"),
      ingredient("1 tsp", "cinnamon", "pantry"),
      ingredient("1 tbsp", "maple syrup", "pantry"),
      ingredient("1", "banana", "produce"),
    ],
    steps: [
      "Simmer cooked or raw rice with extra water until soft and porridgy.",
      "Stir in cinnamon.",
      "Slice the banana.",
      "Sweeten with maple syrup at the table.",
    ],
  },
  {
    id: "veggie-scramble",
    title: "Spinach potato scramble",
    blurb: "Eggs, potato, and spinach when eggs are welcome.",
    slot: "breakfast",
    minutes: 15,
    cuisine: "American",
    vegetarian: true,
    contains: ["egg"],
    tags: ["vegetarian", "breakfast"],
    ingredients: [
      ingredient("3", "eggs", "dairy"),
      ingredient("2 cups", "spinach", "produce"),
      ingredient("1", "potato", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Dice and pan-fry the potato in olive oil until tender.",
      "Beat the eggs with a pinch of salt.",
      "Add spinach, then eggs, and scramble gently.",
      "Eat it straight from the pan.",
    ],
  },
  {
    id: "yogurt-cucumber-bowl",
    title: "Yogurt cucumber bowl",
    blurb: "Cold, fast, and clearly dairy. Leave it off the plan when milk is excluded.",
    slot: "breakfast",
    minutes: 10,
    cuisine: "Mediterranean",
    vegetarian: true,
    contains: ["dairy"],
    tags: ["vegetarian", "breakfast"],
    ingredients: [
      ingredient("1 cup", "yogurt", "dairy"),
      ingredient("1", "cucumber", "produce"),
      ingredient("1 tsp", "dill", "produce"),
      ingredient("1", "lemon", "produce"),
    ],
    steps: [
      "Dice the cucumber.",
      "Stir yogurt with lemon juice, dill, and a pinch of salt.",
      "Fold in the cucumber.",
      "Serve cold.",
    ],
  },
  {
    id: "sweet-potato-breakfast-hash",
    title: "Sweet potato breakfast hash",
    blurb: "A savory plate that still fits a short morning.",
    slot: "breakfast",
    minutes: 20,
    cuisine: "Mexican",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "breakfast"],
    ingredients: [
      ingredient("1", "sweet potato", "produce"),
      ingredient("1/2 can", "black beans", "protein"),
      ingredient("1/4 cup", "salsa", "pantry"),
      ingredient("1", "lime", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Dice and skillet-cook the sweet potato in olive oil.",
      "Warm the black beans beside it.",
      "Spoon on salsa.",
      "Finish with lime. Check the salsa jar.",
    ],
  },
  {
    id: "mango-chia-cup",
    title: "Mango chia cup",
    blurb: "Coconut milk and fruit, stirred together while the kettle boils.",
    slot: "breakfast",
    minutes: 10,
    cuisine: "American",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "breakfast"],
    ingredients: [
      ingredient("3 tbsp", "chia seeds", "pantry"),
      ingredient("1", "mango", "produce"),
      ingredient("1/2 cup", "coconut milk", "pantry"),
      ingredient("1", "lime", "produce"),
    ],
    steps: [
      "Stir chia seeds into coconut milk and let them thicken for a few minutes.",
      "Dice the mango.",
      "Spoon mango over the chia.",
      "Finish with lime.",
    ],
  },
  {
    id: "apple-quinoa-breakfast",
    title: "Apple cinnamon quinoa",
    blurb: "Breakfast quinoa for mornings when oats are the wrong grain.",
    slot: "breakfast",
    minutes: 15,
    cuisine: "American",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "breakfast"],
    ingredients: [
      ingredient("1 cup", "quinoa", "pantry"),
      ingredient("1", "apple", "produce"),
      ingredient("1 tsp", "cinnamon", "pantry"),
      ingredient("1 tbsp", "maple syrup", "pantry"),
    ],
    steps: [
      "Simmer quinoa until tender.",
      "Dice the apple and fold it in with cinnamon.",
      "Add a spoon of water if it looks dry.",
      "Drizzle maple syrup to finish.",
    ],
  },
  {
    id: "lemon-lentil-soup",
    title: "Lemon lentil soup",
    blurb: "A pot of lentils, carrot, and lemon that reheats for a second lunch.",
    slot: "lunch",
    minutes: 25,
    cuisine: "Mediterranean",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "lunch"],
    ingredients: [
      ingredient("1 cup", "red lentils", "protein"),
      ingredient("2", "carrot", "produce"),
      ingredient("1 stalk", "celery", "produce"),
      ingredient("1", "lemon", "produce"),
      ingredient("1 tsp", "cumin", "pantry"),
      ingredient("2 cloves", "garlic", "produce"),
    ],
    steps: [
      "Chop carrot, celery, and garlic.",
      "Simmer them with rinsed lentils, cumin, and water until the lentils fall apart.",
      "Salt and add lemon juice.",
      "Ladle into bowls. It thickens in the fridge, so loosen leftovers with water.",
    ],
  },
  {
    id: "chickpea-stuffed-tomatoes",
    title: "Chickpea stuffed tomatoes",
    blurb: "A no-cook-ish lunch if the chickpeas are already in the pantry.",
    slot: "lunch",
    minutes: 15,
    cuisine: "Mediterranean",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "lunch"],
    ingredients: [
      ingredient("2", "tomato", "produce"),
      ingredient("1 can", "chickpeas", "protein"),
      ingredient("1 handful", "parsley", "produce"),
      ingredient("1", "lemon", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Cut the tops off the tomatoes and scoop out a little of the center.",
      "Mash half the chickpeas with lemon, olive oil, and parsley.",
      "Fold in the rest of the chickpeas and the tomato scraps.",
      "Stuff the tomatoes and eat them cold or at room temperature.",
    ],
  },
  {
    id: "hummus-veggie-wrap",
    title: "Hummus veggie wrap",
    blurb: "A wheat wrap with tahini. It steps aside for gluten or sesame exclusions.",
    slot: "lunch",
    minutes: 15,
    cuisine: "Mediterranean",
    vegetarian: true,
    contains: ["gluten", "sesame"],
    tags: ["vegetarian", "lunch"],
    ingredients: [
      ingredient("2", "wheat tortilla", "bakery"),
      ingredient("1/2 cup", "hummus", "protein"),
      ingredient("1", "cucumber", "produce"),
      ingredient("1 tbsp", "tahini", "pantry"),
      ingredient("1", "tomato", "produce"),
    ],
    steps: [
      "Stir tahini into the hummus if you want it richer, after you have checked both labels.",
      "Slice cucumber and tomato.",
      "Spread hummus on the wheat tortillas.",
      "Roll tightly and slice in half.",
    ],
  },
  {
    id: "rice-noodle-veggie-bowl",
    title: "Rice noodle veggie bowl",
    blurb: "Rice noodles with cabbage, carrot, lime, and ginger.",
    slot: "lunch",
    minutes: 20,
    cuisine: "Japanese",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "lunch"],
    ingredients: [
      ingredient("6 oz", "rice noodles", "pantry"),
      ingredient("2 cups", "cabbage", "produce"),
      ingredient("1", "carrot", "produce"),
      ingredient("1", "lime", "produce"),
      ingredient("1 tbsp", "ginger", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Soak or boil the rice noodles until tender, then rinse them.",
      "Shred cabbage and carrot.",
      "Toss with olive oil, grated ginger, lime juice, and salt.",
      "Taste before adding any shared sauce from the fridge door.",
    ],
  },
  {
    id: "tomato-basil-bean-soup",
    title: "Tomato basil bean soup",
    blurb: "A blender-optional soup that is mostly a can of beans and ripe tomatoes.",
    slot: "lunch",
    minutes: 20,
    cuisine: "Italian",
    vegetarian: true,
    contains: [],
    tags: ["vegetarian", "lunch"],
    ingredients: [
      ingredient("3", "tomato", "produce"),
      ingredient("1 can", "cannellini beans", "protein"),
      ingredient("1 handful", "basil", "produce"),
      ingredient("2 cloves", "garlic", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Simmer chopped tomato and garlic in olive oil with a pinch of salt.",
      "Add drained beans and a splash of water.",
      "Mash some of the beans so the soup turns silky.",
      "Stir in basil just before serving.",
    ],
  },
  {
    id: "mediterranean-couscous",
    title: "Mediterranean couscous",
    blurb: "A quick couscous salad. Olives are in the bowl, so dislike filters can drop it.",
    slot: "lunch",
    minutes: 20,
    cuisine: "Mediterranean",
    vegetarian: true,
    contains: ["gluten"],
    tags: ["vegetarian", "lunch"],
    ingredients: [
      ingredient("1 cup", "couscous", "pantry"),
      ingredient("1", "cucumber", "produce"),
      ingredient("1", "tomato", "produce"),
      ingredient("1/2 can", "chickpeas", "protein"),
      ingredient("1/4 cup", "olives", "produce"),
      ingredient("1", "lemon", "produce"),
      ingredient("1 tbsp", "olive oil", "pantry"),
    ],
    steps: [
      "Cover couscous with boiling water, cover the bowl, and wait five minutes.",
      "Fluff it with a fork.",
      "Chop cucumber, tomato, and olives.",
      "Toss with chickpeas, lemon, and olive oil.",
    ],
  },
  {
    id: "tofu-rice-bowl",
    title: "Tofu rice bowl",
    blurb: "Crisp tofu over rice with cucumber, tamari, and lime.",
    slot: "lunch",
    minutes: 20,
    cuisine: "Japanese",
    vegetarian: true,
    contains: ["soy"],
    tags: ["vegetarian", "lunch"],
    ingredients: [
      ingredient("8 oz", "tofu", "protein"),
      ingredient("1 cup", "rice", "pantry"),
      ingredient("1", "cucumber", "produce"),
      ingredient("1", "carrot", "produce"),
      ingredient("1 tbsp", "tamari", "pantry"),
      ingredient("1", "lime", "produce"),
    ],
    steps: [
      "Start the rice and cube the tofu.",
      "Sear tofu in a bare nonstick pan or a little oil you have cleared.",
      "Slice cucumber and carrot.",
      "Serve with tamari and lime on the side so the amount stays yours to choose.",
    ],
  },
];

export function recipesForSlot(slot: Recipe["slot"]): Recipe[] {
  return RECIPES.filter((recipe) => recipe.slot === slot);
}
